package dataservices.map;
// Generated Sep 12, 2016 9:35:08 PM by Hibernate Tools 3.6.0



/**
 * Almacen generated by hbm2java
 */
public class Almacen  implements java.io.Serializable {


     private Integer idAlmacen;
     private String almNombre;
     private String almCiudad;

    public Almacen() {
    }

    public Almacen(String almNombre, String almCiudad) {
       this.almNombre = almNombre;
       this.almCiudad = almCiudad;
    }
   
    public Integer getIdAlmacen() {
        return this.idAlmacen;
    }
    
    public void setIdAlmacen(Integer idAlmacen) {
        this.idAlmacen = idAlmacen;
    }
    public String getAlmNombre() {
        return this.almNombre;
    }
    
    public void setAlmNombre(String almNombre) {
        this.almNombre = almNombre;
    }
    public String getAlmCiudad() {
        return this.almCiudad;
    }
    
    public void setAlmCiudad(String almCiudad) {
        this.almCiudad = almCiudad;
    }




}


