package dataservices.map;
// Generated Sep 12, 2016 9:35:08 PM by Hibernate Tools 3.6.0



/**
 * Canton generated by hbm2java
 */
public class Canton  implements java.io.Serializable {


     private Integer idCanton;
     private Integer idProvincia;
     private String canNombre;

    public Canton() {
    }

    public Canton(Integer idProvincia, String canNombre) {
       this.idProvincia = idProvincia;
       this.canNombre = canNombre;
    }
   
    public Integer getIdCanton() {
        return this.idCanton;
    }
    
    public void setIdCanton(Integer idCanton) {
        this.idCanton = idCanton;
    }
    public Integer getIdProvincia() {
        return this.idProvincia;
    }
    
    public void setIdProvincia(Integer idProvincia) {
        this.idProvincia = idProvincia;
    }
    public String getCanNombre() {
        return this.canNombre;
    }
    
    public void setCanNombre(String canNombre) {
        this.canNombre = canNombre;
    }




}


