package dataservices.map;
// Generated Sep 12, 2016 9:35:08 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Integer idCliente;
     private String cliNombres;
     private String cliCedula;
     private String cliTelefono;
     private String cliMovil;
     private String cliDireccion;
     private String cliReferencia;
     private String cliProvincia;
     private String cliCanton;
     private String cliParroquia;
     private Set ordens = new HashSet(0);

    public Cliente() {
       
    }

    public Cliente(String cliNombres, String cliCedula, String cliTelefono, String cliMovil, String cliDireccion, String cliReferencia, String cliProvincia, String cliCanton, String cliParroquia, Set ordens) {
       this.cliNombres = cliNombres;
       this.cliCedula = cliCedula;
       this.cliTelefono = cliTelefono;
       this.cliMovil = cliMovil;
       this.cliDireccion = cliDireccion;
       this.cliReferencia = cliReferencia;
       this.cliProvincia = cliProvincia;
       this.cliCanton = cliCanton;
       this.cliParroquia = cliParroquia;
       this.ordens = ordens;
    }
   
    public Integer getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }
    public String getCliNombres() {
        return this.cliNombres;
    }
    
    public void setCliNombres(String cliNombres) {
        this.cliNombres = cliNombres;
    }
    public String getCliCedula() {
        return this.cliCedula;
    }
    
    public void setCliCedula(String cliCedula) {
        this.cliCedula = cliCedula;
    }
    public String getCliTelefono() {
        return this.cliTelefono;
    }
    
    public void setCliTelefono(String cliTelefono) {
        this.cliTelefono = cliTelefono;
    }
    public String getCliMovil() {
        return this.cliMovil;
    }
    
    public void setCliMovil(String cliMovil) {
        this.cliMovil = cliMovil;
    }
    public String getCliDireccion() {
        return this.cliDireccion;
    }
    
    public void setCliDireccion(String cliDireccion) {
        this.cliDireccion = cliDireccion;
    }
    public String getCliReferencia() {
        return this.cliReferencia;
    }
    
    public void setCliReferencia(String cliReferencia) {
        this.cliReferencia = cliReferencia;
    }
    public String getCliProvincia() {
        return this.cliProvincia;
    }
    
    public void setCliProvincia(String cliProvincia) {
        this.cliProvincia = cliProvincia;
    }
    public String getCliCanton() {
        return this.cliCanton;
    }
    
    public void setCliCanton(String cliCanton) {
        this.cliCanton = cliCanton;
    }
    public String getCliParroquia() {
        return this.cliParroquia;
    }
    
    public void setCliParroquia(String cliParroquia) {
        this.cliParroquia = cliParroquia;
    }
    public Set getOrdens() {
        return this.ordens;
    }
    
    public void setOrdens(Set ordens) {
        this.ordens = ordens;
    }




}


