package dataservices.map;
// Generated Sep 12, 2016 9:35:08 PM by Hibernate Tools 3.6.0



/**
 * DetallleR generated by hbm2java
 */
public class DetallleR  implements java.io.Serializable {


     private Integer idDetalleR;
     private Orden orden;
     private Repuesto repuesto;
     private Integer detallleRCantidad;
     private Double detallleRValor;

    public DetallleR() {
        this.orden = new Orden();
        this.repuesto = new Repuesto();
        this.detallleRCantidad = 0;
        this.detallleRValor = 0.0;
    }

	
    public DetallleR(Orden orden, Repuesto repuesto) {
        this.orden = orden;
        this.repuesto = repuesto;
    }
    public DetallleR(Orden orden, Repuesto repuesto, Integer detallleRCantidad, Double detallleRValor) {
       this.orden = orden;
       this.repuesto = repuesto;
       this.detallleRCantidad = detallleRCantidad;
       this.detallleRValor = detallleRValor;
    }
   
    public Integer getIdDetalleR() {
        return this.idDetalleR;
    }
    
    public void setIdDetalleR(Integer idDetalleR) {
        this.idDetalleR = idDetalleR;
    }
    public Orden getOrden() {
        return this.orden;
    }
    
    public void setOrden(Orden orden) {
        this.orden = orden;
    }
    public Repuesto getRepuesto() {
        return this.repuesto;
    }
    
    public void setRepuesto(Repuesto repuesto) {
        this.repuesto = repuesto;
    }
    public Integer getDetallleRCantidad() {
        return this.detallleRCantidad;
    }
    
    public void setDetallleRCantidad(Integer detallleRCantidad) {
        this.detallleRCantidad = detallleRCantidad;
    }
    public Double getDetallleRValor() {
        return this.detallleRValor;
    }
    
    public void setDetallleRValor(Double detallleRValor) {
        this.detallleRValor = detallleRValor;
    }




}


