package dataservices.map;
// Generated Sep 12, 2016 9:35:08 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Estado generated by hbm2java
 */
public class Estado  implements java.io.Serializable {


     private Integer idEstado;
     private String estNombre;
     private Set registros = new HashSet(0);

    public Estado() {
    }

    public Estado(String estNombre, Set registros) {
       this.estNombre = estNombre;
       this.registros = registros;
    }
   
    public Integer getIdEstado() {
        return this.idEstado;
    }
    
    public void setIdEstado(Integer idEstado) {
        this.idEstado = idEstado;
    }
    public String getEstNombre() {
        return this.estNombre;
    }
    
    public void setEstNombre(String estNombre) {
        this.estNombre = estNombre;
    }
    public Set getRegistros() {
        return this.registros;
    }
    
    public void setRegistros(Set registros) {
        this.registros = registros;
    }




}


