package dataservices.map;
// Generated Sep 12, 2016 9:35:08 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Garantia generated by hbm2java
 */
public class Garantia  implements java.io.Serializable {


     private Integer idGarantia;
     private Producto producto;
     private Date garFechaFactura;
     private String garAlmacen;
     private String garTelefonoAlmacen;
     private String garNumFactura;
     private Integer garFlag;

    public Garantia() {
        this.producto = new Producto();
        this.garFechaFactura = new Date();
        this.garFlag = 1;
    }

	
    public Garantia(Producto producto) {
        this.producto = producto;
    }
    public Garantia(Producto producto, Date garFechaFactura, String garAlmacen, String garTelefonoAlmacen, String garNumFactura, Integer garFlag) {
       this.producto = producto;
       this.garFechaFactura = garFechaFactura;
       this.garAlmacen = garAlmacen;
       this.garTelefonoAlmacen = garTelefonoAlmacen;
       this.garNumFactura = garNumFactura;
       this.garFlag = garFlag;
    }
   
    public Integer getIdGarantia() {
        return this.idGarantia;
    }
    
    public void setIdGarantia(Integer idGarantia) {
        this.idGarantia = idGarantia;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Date getGarFechaFactura() {
        return this.garFechaFactura;
    }
    
    public void setGarFechaFactura(Date garFechaFactura) {
        this.garFechaFactura = garFechaFactura;
    }
    public String getGarAlmacen() {
        return this.garAlmacen;
    }
    
    public void setGarAlmacen(String garAlmacen) {
        this.garAlmacen = garAlmacen;
    }
    public String getGarTelefonoAlmacen() {
        return this.garTelefonoAlmacen;
    }
    
    public void setGarTelefonoAlmacen(String garTelefonoAlmacen) {
        this.garTelefonoAlmacen = garTelefonoAlmacen;
    }
    public String getGarNumFactura() {
        return this.garNumFactura;
    }
    
    public void setGarNumFactura(String garNumFactura) {
        this.garNumFactura = garNumFactura;
    }
    public Integer getGarFlag() {
        return this.garFlag;
    }
    
    public void setGarFlag(Integer garFlag) {
        this.garFlag = garFlag;
    }




}


