package dataservices.map;
// Generated Sep 12, 2016 9:35:08 PM by Hibernate Tools 3.6.0



/**
 * Parroquia generated by hbm2java
 */
public class Parroquia  implements java.io.Serializable {


     private Integer idParroquia;
     private Integer idCanton;
     private String parrNombre;

    public Parroquia() {
    }

    public Parroquia(Integer idCanton, String parrNombre) {
       this.idCanton = idCanton;
       this.parrNombre = parrNombre;
    }
   
    public Integer getIdParroquia() {
        return this.idParroquia;
    }
    
    public void setIdParroquia(Integer idParroquia) {
        this.idParroquia = idParroquia;
    }
    public Integer getIdCanton() {
        return this.idCanton;
    }
    
    public void setIdCanton(Integer idCanton) {
        this.idCanton = idCanton;
    }
    public String getParrNombre() {
        return this.parrNombre;
    }
    
    public void setParrNombre(String parrNombre) {
        this.parrNombre = parrNombre;
    }




}


