package dataservices.map;
// Generated Sep 12, 2016 9:35:08 PM by Hibernate Tools 3.6.0



/**
 * Pro generated by hbm2java
 */
public class Pro  implements java.io.Serializable {


     private Integer idNpro;
     private String nproNombre;

    public Pro() {
    }

    public Pro(String nproNombre) {
       this.nproNombre = nproNombre;
    }
   
    public Integer getIdNpro() {
        return this.idNpro;
    }
    
    public void setIdNpro(Integer idNpro) {
        this.idNpro = idNpro;
    }
    public String getNproNombre() {
        return this.nproNombre;
    }
    
    public void setNproNombre(String nproNombre) {
        this.nproNombre = nproNombre;
    }




}


