package dataservices.map;
// Generated Sep 12, 2016 9:35:08 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private Integer idPro;
     private Integer proNumSis;
     private String proNombre;
     private String proMarca;
     private String proModelo;
     private String proSerie;
     private String proCod1;
     private String proCod2;
     private String proCod3;
     private Set garantias = new HashSet(0);
     private Set ordens = new HashSet(0);

    public Producto() {
    }

    public Producto(Integer proNumSis, String proNombre, String proMarca, String proModelo, String proSerie, String proCod1, String proCod2, String proCod3, Set garantias, Set ordens) {
       this.proNumSis = proNumSis;
       this.proNombre = proNombre;
       this.proMarca = proMarca;
       this.proModelo = proModelo;
       this.proSerie = proSerie;
       this.proCod1 = proCod1;
       this.proCod2 = proCod2;
       this.proCod3 = proCod3;
       this.garantias = garantias;
       this.ordens = ordens;
    }
   
    public Integer getIdPro() {
        return this.idPro;
    }
    
    public void setIdPro(Integer idPro) {
        this.idPro = idPro;
    }
    public Integer getProNumSis() {
        return this.proNumSis;
    }
    
    public void setProNumSis(Integer proNumSis) {
        this.proNumSis = proNumSis;
    }
    public String getProNombre() {
        return this.proNombre;
    }
    
    public void setProNombre(String proNombre) {
        this.proNombre = proNombre;
    }
    public String getProMarca() {
        return this.proMarca;
    }
    
    public void setProMarca(String proMarca) {
        this.proMarca = proMarca;
    }
    public String getProModelo() {
        return this.proModelo;
    }
    
    public void setProModelo(String proModelo) {
        this.proModelo = proModelo;
    }
    public String getProSerie() {
        return this.proSerie;
    }
    
    public void setProSerie(String proSerie) {
        this.proSerie = proSerie;
    }
    public String getProCod1() {
        return this.proCod1;
    }
    
    public void setProCod1(String proCod1) {
        this.proCod1 = proCod1;
    }
    public String getProCod2() {
        return this.proCod2;
    }
    
    public void setProCod2(String proCod2) {
        this.proCod2 = proCod2;
    }
    public String getProCod3() {
        return this.proCod3;
    }
    
    public void setProCod3(String proCod3) {
        this.proCod3 = proCod3;
    }
    public Set getGarantias() {
        return this.garantias;
    }
    
    public void setGarantias(Set garantias) {
        this.garantias = garantias;
    }
    public Set getOrdens() {
        return this.ordens;
    }
    
    public void setOrdens(Set ordens) {
        this.ordens = ordens;
    }




}


