package dataservices.map;
// Generated Sep 12, 2016 9:35:08 PM by Hibernate Tools 3.6.0



/**
 * Provincia generated by hbm2java
 */
public class Provincia  implements java.io.Serializable {


     private Integer idProvincia;
     private String provNombre;

    public Provincia() {
    }

    public Provincia(String provNombre) {
       this.provNombre = provNombre;
    }
   
    public Integer getIdProvincia() {
        return this.idProvincia;
    }
    
    public void setIdProvincia(Integer idProvincia) {
        this.idProvincia = idProvincia;
    }
    public String getProvNombre() {
        return this.provNombre;
    }
    
    public void setProvNombre(String provNombre) {
        this.provNombre = provNombre;
    }




}


