package dataservices.map;
// Generated Sep 12, 2016 9:35:08 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Registro generated by hbm2java
 */
public class Registro  implements java.io.Serializable {


     private Integer idReg;
     private Orden orden;
     private Funcionarios funcionarios;
     private Estado estado;
     private Date regFecha;

    public Registro() {
        this.orden = new Orden();
        this.funcionarios = new Funcionarios();
        this.estado = new Estado();
    }

	
    public Registro(Orden orden, Funcionarios funcionarios, Estado estado) {
        this.orden = orden;
        this.funcionarios = funcionarios;
        this.estado = estado;
    }
    public Registro(Orden orden, Funcionarios funcionarios, Estado estado, Date regFecha) {
       this.orden = orden;
       this.funcionarios = funcionarios;
       this.estado = estado;
       this.regFecha = regFecha;
    }
   
    public Integer getIdReg() {
        return this.idReg;
    }
    
    public void setIdReg(Integer idReg) {
        this.idReg = idReg;
    }
    public Orden getOrden() {
        return this.orden;
    }
    
    public void setOrden(Orden orden) {
        this.orden = orden;
    }
    public Funcionarios getFuncionarios() {
        return this.funcionarios;
    }
    
    public void setFuncionarios(Funcionarios funcionarios) {
        this.funcionarios = funcionarios;
    }
    public Estado getEstado() {
        return this.estado;
    }
    
    public void setEstado(Estado estado) {
        this.estado = estado;
    }
    public Date getRegFecha() {
        return this.regFecha;
    }
    
    public void setRegFecha(Date regFecha) {
        this.regFecha = regFecha;
    }




}


