package dataservices.map;
// Generated Sep 12, 2016 9:35:08 PM by Hibernate Tools 3.6.0



/**
 * Rep generated by hbm2java
 */
public class Rep  implements java.io.Serializable {


     private Integer idNrep;
     private String nrepNombre;

    public Rep() {
    }

    public Rep(String nrepNombre) {
       this.nrepNombre = nrepNombre;
    }
   
    public Integer getIdNrep() {
        return this.idNrep;
    }
    
    public void setIdNrep(Integer idNrep) {
        this.idNrep = idNrep;
    }
    public String getNrepNombre() {
        return this.nrepNombre;
    }
    
    public void setNrepNombre(String nrepNombre) {
        this.nrepNombre = nrepNombre;
    }




}


