package dataservices.map;
// Generated Sep 12, 2016 9:35:08 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Repuesto generated by hbm2java
 */
public class Repuesto  implements java.io.Serializable {


     private Integer idRes;
     private String repNombre;
     private String repMarca;
     private String repNumPart;
     private String repCod1;
     private String repCod2;
     private String repCod3;
     private Set detallleRs = new HashSet(0);

    public Repuesto() {
    }

    public Repuesto(String repNombre, String repMarca, String repNumPart, String repCod1, String repCod2, String repCod3, Set detallleRs) {
       this.repNombre = repNombre;
       this.repMarca = repMarca;
       this.repNumPart = repNumPart;
       this.repCod1 = repCod1;
       this.repCod2 = repCod2;
       this.repCod3 = repCod3;
       this.detallleRs = detallleRs;
    }
   
    public Integer getIdRes() {
        return this.idRes;
    }
    
    public void setIdRes(Integer idRes) {
        this.idRes = idRes;
    }
    public String getRepNombre() {
        return this.repNombre;
    }
    
    public void setRepNombre(String repNombre) {
        this.repNombre = repNombre;
    }
    public String getRepMarca() {
        return this.repMarca;
    }
    
    public void setRepMarca(String repMarca) {
        this.repMarca = repMarca;
    }
    public String getRepNumPart() {
        return this.repNumPart;
    }
    
    public void setRepNumPart(String repNumPart) {
        this.repNumPart = repNumPart;
    }
    public String getRepCod1() {
        return this.repCod1;
    }
    
    public void setRepCod1(String repCod1) {
        this.repCod1 = repCod1;
    }
    public String getRepCod2() {
        return this.repCod2;
    }
    
    public void setRepCod2(String repCod2) {
        this.repCod2 = repCod2;
    }
    public String getRepCod3() {
        return this.repCod3;
    }
    
    public void setRepCod3(String repCod3) {
        this.repCod3 = repCod3;
    }
    public Set getDetallleRs() {
        return this.detallleRs;
    }
    
    public void setDetallleRs(Set detallleRs) {
        this.detallleRs = detallleRs;
    }




}


