package dataservices.map;
// Generated Sep 12, 2016 9:35:08 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Rol generated by hbm2java
 */
public class Rol  implements java.io.Serializable {


     private Integer idRol;
     private String rolTipo;
     private Set funcionarioses = new HashSet(0);

    public Rol() {
    }

    public Rol(String rolTipo, Set funcionarioses) {
       this.rolTipo = rolTipo;
       this.funcionarioses = funcionarioses;
    }
   
    public Integer getIdRol() {
        return this.idRol;
    }
    
    public void setIdRol(Integer idRol) {
        this.idRol = idRol;
    }
    public String getRolTipo() {
        return this.rolTipo;
    }
    
    public void setRolTipo(String rolTipo) {
        this.rolTipo = rolTipo;
    }
    public Set getFuncionarioses() {
        return this.funcionarioses;
    }
    
    public void setFuncionarioses(Set funcionarioses) {
        this.funcionarioses = funcionarioses;
    }




}


