package dataservices.map;
// Generated Sep 12, 2016 9:35:08 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Servicio generated by hbm2java
 */
public class Servicio  implements java.io.Serializable {


     private Integer idCentro;
     private String serNombre;
     private String serTelefono;
     private String serRepresentante1;
     private String serRepresentante2;
     private Set funcionarioses = new HashSet(0);

    public Servicio() {
    }

    public Servicio(String serNombre, String serTelefono, String serRepresentante1, String serRepresentante2, Set funcionarioses) {
       this.serNombre = serNombre;
       this.serTelefono = serTelefono;
       this.serRepresentante1 = serRepresentante1;
       this.serRepresentante2 = serRepresentante2;
       this.funcionarioses = funcionarioses;
    }
   
    public Integer getIdCentro() {
        return this.idCentro;
    }
    
    public void setIdCentro(Integer idCentro) {
        this.idCentro = idCentro;
    }
    public String getSerNombre() {
        return this.serNombre;
    }
    
    public void setSerNombre(String serNombre) {
        this.serNombre = serNombre;
    }
    public String getSerTelefono() {
        return this.serTelefono;
    }
    
    public void setSerTelefono(String serTelefono) {
        this.serTelefono = serTelefono;
    }
    public String getSerRepresentante1() {
        return this.serRepresentante1;
    }
    
    public void setSerRepresentante1(String serRepresentante1) {
        this.serRepresentante1 = serRepresentante1;
    }
    public String getSerRepresentante2() {
        return this.serRepresentante2;
    }
    
    public void setSerRepresentante2(String serRepresentante2) {
        this.serRepresentante2 = serRepresentante2;
    }
    public Set getFuncionarioses() {
        return this.funcionarioses;
    }
    
    public void setFuncionarioses(Set funcionarioses) {
        this.funcionarioses = funcionarioses;
    }




}


