package dataservices.map;
// Generated Sep 12, 2016 9:35:08 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Sesion generated by hbm2java
 */
public class Sesion  implements java.io.Serializable {


     private Integer idSesion;
     private Funcionarios funcionarios;
     private Date sesFecha;
     private String sesEstado;

    public Sesion() {
    }

	
    public Sesion(Funcionarios funcionarios) {
        this.funcionarios = funcionarios;
    }
    public Sesion(Funcionarios funcionarios, Date sesFecha, String sesEstado) {
       this.funcionarios = funcionarios;
       this.sesFecha = sesFecha;
       this.sesEstado = sesEstado;
    }
   
    public Integer getIdSesion() {
        return this.idSesion;
    }
    
    public void setIdSesion(Integer idSesion) {
        this.idSesion = idSesion;
    }
    public Funcionarios getFuncionarios() {
        return this.funcionarios;
    }
    
    public void setFuncionarios(Funcionarios funcionarios) {
        this.funcionarios = funcionarios;
    }
    public Date getSesFecha() {
        return this.sesFecha;
    }
    
    public void setSesFecha(Date sesFecha) {
        this.sesFecha = sesFecha;
    }
    public String getSesEstado() {
        return this.sesEstado;
    }
    
    public void setSesEstado(String sesEstado) {
        this.sesEstado = sesEstado;
    }




}


