package dataservices.map;
// Generated Sep 12, 2016 9:35:08 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idUsuario;
     private Funcionarios funcionarios;
     private String usuNombre;
     private String usuClaveSecreta;
     private Date usuFecha;
     private Integer usuFlag;

    public Usuario() {
        this.funcionarios = new Funcionarios();
    }

	
    public Usuario(Funcionarios funcionarios) {
        this.funcionarios = funcionarios;
    }
    public Usuario(Funcionarios funcionarios, String usuNombre, String usuClaveSecreta, Date usuFecha, Integer usuFlag) {
       this.funcionarios = funcionarios;
       this.usuNombre = usuNombre;
       this.usuClaveSecreta = usuClaveSecreta;
       this.usuFecha = usuFecha;
       this.usuFlag = usuFlag;
    }
   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Funcionarios getFuncionarios() {
        return this.funcionarios;
    }
    
    public void setFuncionarios(Funcionarios funcionarios) {
        this.funcionarios = funcionarios;
    }
    public String getUsuNombre() {
        return this.usuNombre;
    }
    
    public void setUsuNombre(String usuNombre) {
        this.usuNombre = usuNombre;
    }
    public String getUsuClaveSecreta() {
        return this.usuClaveSecreta;
    }
    
    public void setUsuClaveSecreta(String usuClaveSecreta) {
        this.usuClaveSecreta = usuClaveSecreta;
    }
    public Date getUsuFecha() {
        return this.usuFecha;
    }
    
    public void setUsuFecha(Date usuFecha) {
        this.usuFecha = usuFecha;
    }
    public Integer getUsuFlag() {
        return this.usuFlag;
    }
    
    public void setUsuFlag(Integer usuFlag) {
        this.usuFlag = usuFlag;
    }




}


